# Site settings
title: BRDDG
email: john@brddg.co
description: > # this means to ignore newlines until "baseurl:"
  BRDDG is a multidisciplinary creative collective building
  unique digital, print, and interactive solutions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brddg.co" # the base hostname & protocol for your site
twitter_username: brddg
github_username:  brddg

# Build settings
markdown: kramdown

sass:
  style: :compressed
